spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: xsn-site-config-jiazd-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: xsn-site-config-jiazd-test
#  请保存为UTF-8格式
 
 
